### ISSUE TITLE
Convergence LRMC

### ISSUE THREAD

**Issue by martintsd** [YoucefZemmouri/Unsupervised_Learning_P1#1]
https://github.com/YoucefZemmouri/Unsupervised_Learning_P1/blob/3a80c96915cfb9413d3827fb15c3ce2ebfc212a2/tools.py#L69

Ce serait peut-être mieux de mettre "Pro_WX - W_1 * A" au lieu de "Z - Z_prev" car "Z - Z_prev" dépend du beta

**Comment by flm8620** [comment]
Je suis d'accord, "Pro_WX - W_1 * A" est de gradient de L par rapport à Z, c'est ça qu'on doit mesurer

**Comment by flm8620** [comment]
C'est peut-être aussi mieux de contrôler le np.max(abs(Pro_WX - W_1 * A)) au lieu de np.mean(abs(Pro_WX - W_1 * A))

**Comment by martintsd** [comment]
Bonne idée !
