### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by martintsd** [YoucefZemmouri/Unsupervised_Learning_P1#2]
Mon code fonctionne mais est très lent, pourriez-vous jeter un oeil ?

https://github.com/YoucefZemmouri/Unsupervised_Learning_P1/blob/master/P3_matrix_completion.py

**Comment by flm8620** [comment]
essayer de jouer sur beta. Je me souviens que quand beta = 2, parfois il diverge (pour question 2, c'est comme ça ).
Je pense beta dois être strictement inférieur à 2. Essayer beta =1.8 ou 1.9

**Comment by flm8620** [comment]
J'ai testé. Beta = 1.8, epsilon = 1. Algo termine dans 184 itérations, 106 seconds

**Comment by flm8620** [comment]
J'ai commité et ajouté des commentaires. J'ajoute aussi affichage de pas dans LRMC

**Comment by martintsd** [comment]
Super. Je fais des mesures d'erreur en variant tau.
