### ISSUE TITLE
Résultats

### ISSUE THREAD

**Issue by martintsd** [YoucefZemmouri/Unsupervised_Learning_P1#3]
Le programme est lent sur mon ordinateur. 
Pouvez-vous l'essayer sur votre ordinateur ?

Résultats pour l'instant:

tau = 100
beta = 1.8
epsilon = 0.1
82  iterations used,  38.99892997741699  seconds
Mean prediction error (on the whole test set) : 2.38568159469
Maximal prediction error : 5.54582339335

tau = 1000
beta = 1.8
epsilon = 0.1
797  iterations used,  404.8467869758606  seconds
Mean prediction error (on the whole test set) : 1.24640369221
Maximal prediction error : 5.21372367643

tau = 10000
beta = 1.8
epsilon = 0.1
9628  iterations used,  4976.206526994705  seconds
Mean prediction error (on the whole test set) : 0.907026202055
Maximal prediction error : 4.39072648667

**Comment by flm8620** [comment]
C'est normal, le SVD est lent.
Il y a peut-être une astuce : augmenter tau petit à petit 
Selon la phrase dans la page 77:

> If one wants to obtain the solution to the problem (3.28), one can repeat the algorithm with an increasing sequence of 	tau’s and at each run, initialize A with the value previously obtained.

Je vais commiter une version de LRMC avec l'initialization de A

**Comment by flm8620** [comment]
J'ai fait le commit. J'ajoute une option pour initializer de A. Mais il me resemble que augmenter tau petit à petit prend beaucoup plus d'itération qu'avant.

**Comment by flm8620** [comment]
J'ai aussi essayé sur Matlab, même vitesse.

**Comment by YoucefZemmouri** [comment]
Je pense que notre critère de convergence est beaucoup trop précis. Pour tau = 10^6, ça tourne depuis plus de 20 heures là. 
Je vais essayer de mettre la norme de Frobenius pour l'erreur et voir ce que ça donne

**Comment by martintsd** [comment]
@flm8620 @YoucefZemmouri J'ai aussi essayé avec la base de données du prof qui est beaucoup plus petit (matrices de taille 1615 X 231 au lieu de 2397 X 647) ça va beaucoup plus vite. Je pense mettre dans le rapport les expériences avec les 2 bases de sonnées.

J'ai modifié mon fichier `P3_matrix_completion.py` pour pouvoir choisir la base de données :
```
dataset = "original" # If we use the file provided by Réne Vidal
#dataset = "movielens" # If we use the Movielens database we built with P3_movielens.py

RatingsTrain = pd.read_csv("movies-data/"+dataset+"_Train.csv")
RatingsTest = pd.read_csv("movies-data/"+dataset+"_Test.csv")
```
